### Create Room
POST {{url}}/v1/rooms
Content-Type: application/json

{
  "roomName": "Gollum",
  "deck": "1,2,3,4,5"
}

> {%
    client.assert(response.status === 200, "Response status is not 200");
    const roomId = response.body.id;
    // length of an uuid
    client.assert(roomId.length === 36);
    client.global.set("createdRoomId", roomId);
%}


### Connect
WEBSOCKET ws://{{url}}/v1/rooms/subscribe/{{createdRoomId}}?name=Felix


### Publish
POST http://{{url}}/v1/rooms/publish/{{createdRoomId}}
Content-Type: application/json

{
  "message": {
    "type": "room:join",
    "data": null
  }
}

### Health
GET http://{{url}}/v1/health
